version: "2"
services:
  frontend:
    image: semtech/ember-proxy-service:1.1.0
    volumes:
      - ./client/dist:/app
      - ./config/spa-proxy:/config
    links:
      - identifier:backend
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: "mu.semte.ch"
      LETSENCRYPT_HOST: "mu.semte.ch"
      LETSENCRYPT_EMAIL: "madnificent@gmail.com"
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.11.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config