version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:virtuoso-v7.2.0-latest
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/var/lib/virtuoso/db
  resource:
    image: semtech/mu-cl-resources:1.3.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    environment:
      BOOT: mu-cl-resources
    ports:
      - "4080:80"